version: 2
jobs:
  build:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - checkout
      - run:
          name: Do we have a git repo
          command: |
            git status
            git log --pretty=format:'' | wc -l
            git rev-parse HEAD
            git rev-parse HEAD~42
