version: 2.1
orbs:
  docker: circleci/docker@2.2.0

jobs:
  build:
    machine:
      image: ubuntu-2204:2023.04.2
    environment:
      KOSLI_ORG: kosli
      KOSLI_FLOW: loancalculator
      IMAGE_NAME: merkely/loancalculator
    steps: 
      - run:
          name: Install kosli-cli  
          command: |
            sudo sh -c 'echo "deb [trusted=yes] https://apt.fury.io/kosli/ /"  > /etc/apt/sources.list.d/fury.list'
            sudo apt install ca-certificates
            sudo apt update
            sudo apt install kosli
      - checkout
      - run: 
          name: Set docker image tags
          command: |
            echo "IMAGE_TAGGED=${IMAGE_NAME}:$(git log -1 --pretty=%h)" >> "${BASH_ENV}"
            echo "IMAGE_LATEST=${IMAGE_NAME}:latest" >> "${BASH_ENV}"
            source "${BASH_ENV}"
      - run:
          name: Create Kosli Flow
          command: |
            kosli create flow ${KOSLI_FLOW} \
              --description "The loan calculator application" \
              --template "jira" \
              --visibility public
      - run:
          name: Report jira evidence
          command: |
            kosli report evidence commit jira \
              --jira-base-url https://kosli-test.atlassian.net \
              --jira-username jon@kosli.com \
              --name jira
      - docker/check
      - docker/build:
          image: ${IMAGE_TAGGED}
      - docker/push:
          digest-path: /tmp/digest.txt
          image: ${IMAGE_TAGGED}
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
