version: 2
jobs:
  build:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - uses: actions/checkout@v2

      - name: Do we have a git repo
        run:
          command: |
            git status
            git log --pretty=format:'' | wc -l
            git rev-parse HEAD
            git rev-parse HEAD~42
