version: 2
jobs:
  build:
    machine:
      image: ubuntu-2204:2023.04.2
    steps: 
      - run:
          name: Install kosli-cli  
          command: |
            #sh -c 'echo "deb [trusted=yes] https://apt.fury.io/kosli/ /"  > /etc/apt/sources.list.d/fury.list'
            echo apt install ca-certificates
            echo apt update
            echo apt install kosli
      - run: kosli version
      - checkout

