name: Deploy to Production
on:
  workflow_dispatch:
    inputs:
      deploy_commit:
        description: 'Git commit-ish to deploy'
        required: true
        default: 'master'

jobs:
  production_deploy:

    # This is a manually triggered workflow to deploy to production
    # Runs from production branch
    # Do deploy, Log deploy, Merge with master
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        # fetch full history
        fetch-depth: 0
        ref: ${{ github.event.inputs.deploy_commit }}


    - name: Add MERKELY_OWNER and MERKELY_PIPELINE to GITHUB_ENV
      run: |
        cat ./Merkely.env >> ${GITHUB_ENV}


    - name: Make Docker image name available for following steps
      run: |
        echo "IMAGE_TAGGED=${{ secrets.DOCKERHUB_REPO_OWNER }}/loancalculator:$(git log -1 --pretty=%h)" >> ${GITHUB_ENV}


    - name: Deploy to production
      run: |
        docker pull ${{ env.IMAGE_TAGGED }}

        docker run \
            --env MERKELY_COMMAND=control_deployment \
            --env MERKELY_FINGERPRINT=docker://${{ env.IMAGE_TAGGED }} \
            --env MERKELY_OWNER=${{ env.MERKELY_OWNER }} \
            --env MERKELY_PIPELINE=${{ env.MERKELY_PIPELINE }} \
            --env MERKELY_API_TOKEN=${{ secrets.MERKELY_API_TOKEN }} \
            --rm \
            --volume /var/run/docker.sock:/var/run/docker.sock \
            merkely/change

        echo YOUR DEPLOYMENT COMMAND HERE

        docker run \
            --env MERKELY_COMMAND=log_deployment \
            --env MERKELY_FINGERPRINT=docker://${{ env.IMAGE_TAGGED }} \
            --env MERKELY_DESCRIPTION="Deployed to production in pipeline" \
            --env MERKELY_ENVIRONMENT=production \
            --env MERKELY_OWNER=${{ env.MERKELY_OWNER }} \
            --env MERKELY_PIPELINE=${{ env.MERKELY_PIPELINE }} \
            --env MERKELY_API_TOKEN=${{ secrets.MERKELY_API_TOKEN }} \
            --env GITHUB_SERVER_URL \
            --env GITHUB_REPOSITORY \
            --env GITHUB_RUN_ID \
            --rm \
            --volume=/var/run/docker.sock:/var/run/docker.sock \
            merkely/change

        git checkout --track origin/production
        git merge ${{ github.event.inputs.deploy_commit }}
        git push origin production



