name: 3/3 Deploy to Production
on:
  workflow_dispatch:
    inputs:
      deploy_commit:
        description: 'Git commit-ish to deploy'
        required: true
        default: 'master'

jobs:
  production_deploy:

    # This is a manually triggered workflow to deploy to production
    # Runs from production branch
    # Do deploy, Log deploy, Merge with master
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        # fetch full history
        fetch-depth: 0
        ref: ${{ github.event.inputs.deploy_commit }}


    - name: Add MERKELY_OWNER and MERKELY_PIPELINE to GITHUB_ENV
      run: |
        cat ./env-files/github.env >> ${GITHUB_ENV}


    - name: Add Docker image name to GITHUB_ENV
      run: |
        echo "IMAGE_TAGGED=${{ secrets.DOCKERHUB_REPO_OWNER }}/loancalculator:$(git log -1 --pretty=%h)" >> ${GITHUB_ENV}


    - name: Pull the Docker image so Merkely can get its digest
      run: |
        docker pull ${{ env.IMAGE_TAGGED }}


    - name: Short-circuit deployment unless approved for release
      uses: docker://merkely/change:latest
      env:
        MERKELY_COMMAND: control_deployment
        MERKELY_FINGERPRINT: docker://${{ env.IMAGE_TAGGED }}
        MERKELY_OWNER: ${{ env.MERKELY_OWNER }}
        MERKELY_PIPELINE: ${{ env.MERKELY_PIPELINE }}
        MERKELY_API_TOKEN: ${{ secrets.MERKELY_API_TOKEN }}


    - name: Deploy to production
      run: |
        echo YOUR DEPLOYMENT COMMAND HERE


    - name: Log deployment to production in Merkely
      uses: docker://merkely/change:latest
      env:
        MERKELY_COMMAND: log_deployment
        MERKELY_FINGERPRINT: docker://${{ env.IMAGE_TAGGED }}
        MERKELY_DESCRIPTION: "Deployed to production in github pipeline"
        MERKELY_ENVIRONMENT: production
        MERKELY_OWNER: ${{ env.MERKELY_OWNER }}
        MERKELY_PIPELINE: ${{ env.MERKELY_PIPELINE }}
        MERKELY_API_TOKEN: ${{ secrets.MERKELY_API_TOKEN }}


    - name: Update tracking branch
      run: |
        git checkout --track origin/production
        git merge --ff-only ${{ github.event.inputs.deploy_commit }}
        git push origin production



