name: Kosli base reporting

on:
  push
#  pull_request:
#    types: [closed]

env:
  KOSLI_ORG: kosli
  KOSLI_FLOW: loancalculator
  KOSLI_TRAIL: ${{ github.sha }}
  KOSLI_CLI_VERSION: "2.11.7"

jobs:
  on-merge:
    name: Run on merge
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup cli client
        if: ${{ github.event.pull_request.merged == true }}
        uses: kosli-dev/setup-cli-action@v2
        with:
          version: ${{ env.KOSLI_CLI_VERSION }}

      - name: Report jira ticket to kosli
        if: ${{ github.event.pull_request.merged == true }}
        env:
          KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
          KOSLI_JIRA_API_TOKEN: ${{ secrets.KOSLI_JIRA_API_TOKEN }}
        run: |
          kosli attest jira \
            --name jira \
            --jira-base-url https://kosli-team.atlassian.net \
            --jira-username tore@kosli.com \
            --jira-api-token ${KOSLI_JIRA_API_TOKEN} \
            --jira-secondary-source ${{ github.head_ref }} \
            --jira-issue-fields "summary,description"
