name: Merge pull request

on:
  pull_request:
    types: [closed]

jobs:
  on-merge:
    name: Run on merge
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Report jira ticket from branch name to kosli
        env:
          KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
          KOSLI_JIRA_API_TOKEN: ${{ secrets.KOSLI_JIRA_API_TOKEN }}
        run: |
          set -x
          JIRA_EXISTS=""
          kosli attest jira \
            --name jira \
            --flow test-jira \
            --trail run-1 \
            --jira-base-url https://kosli-team.atlassian.net \
            --jira-username tore@kosli.com \
            --jira-api-token ${KOSLI_JIRA_API_TOKEN} \
            --jira-issue-fields "summary" \
            --assert --dry-run 2>&1 | grep "no Jira references are found" && JIRA_EXISTS=false || JIRA_EXISTS=true
          if [ "${JIRA_EXISTS}" == "true" ]; then
            kosli attest jira \
              --name jira \
              --flow test-jira \
              --trail run-1 \
              --jira-base-url https://kosli-team.atlassian.net \
              --jira-username tore@kosli.com \
              --jira-api-token ${KOSLI_JIRA_API_TOKEN} \
              --jira-issue-fields "summary,description,creator"            
