name: 2/3 Request approval in Merkely
on:
  workflow_dispatch:
    inputs:
      deploy_commit:
        description: 'Git commit-ish to approve'
        required: true
        default: 'main'


env:
  MERKELY_OWNER: compliancedb
  MERKELY_PIPELINE: loancalculator
  MERKELY_CLI_VERSION: "1.1.0"
  IMAGE_NAME: merkely/loancalculator


jobs:
  request_approval_in_merkely:

    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        # fetch full history
        fetch-depth: 0
        ref: ${{ github.event.inputs.deploy_commit }}


    - name: Add Docker image name to GITHUB_ENV
      run: |
        echo "IMAGE_TAGGED=${{ secrets.DOCKERHUB_REPO_OWNER }}/loancalculator:$(git log -1 --pretty=%h)" >> ${GITHUB_ENV}


    - name: Pull the Docker image so Merkely can get its digest
      run: |
        docker pull ${{ env.IMAGE_TAGGED }}


    - name: Download Merkely cli client
      id: download-merkely-cli
      run: |
        wget https://github.com/merkely-development/cli/releases/download/v${{ env.MERKELY_CLI_VERSION }}/merkely_${{ env.MERKELY_CLI_VERSION }}_linux_amd64.tar.gz
        tar -xf merkely_${{ env.MERKELY_CLI_VERSION }}_linux_amd64.tar.gz


    - name: Request approval in Merkely
      env:
        MERKELY_API_TOKEN: ${{ secrets.MERKELY_API_TOKEN }}
      run:
        ./merkely pipeline approval request ${{ env.IMAGE_TAGGED }}
          --artifact-type docker
          --description "Approval requested by ${{ github.actor }} in github pipeline"
          --oldest-commit origin/production
          --newest-commit ${{ github.event.inputs.deploy_commit }}
          --repo-root ${{ github.workspace }}





