name: Request approval in Merkely
on:
  workflow_dispatch:
    inputs:
      deploy_commit:
        description: 'Git commit-ish to approve'
        required: true
        default: 'master'

jobs:
  request_approval_in_merkely:

    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        # fetch full history
        fetch-depth: 0
        ref: ${{ github.event.inputs.deploy_commit }}


    - name: Add MERKELY_OWNER and MERKELY_PIPELINE to GITHUB_ENV
      run: |
        cat ./Merkely.env >> ${GITHUB_ENV}


    - name: Make Docker image name available for following steps
      run: |
        echo "IMAGE_TAGGED=${{ secrets.DOCKERHUB_REPO_OWNER }}/loancalculator:$(git log -1 --pretty=%h)" >> ${GITHUB_ENV}


    - name: Pull the Docker image so its digest can be determined
      run: |
        docker pull ${{ env.IMAGE_TAGGED }}


    - name: Request Approval in Merkely
      uses: docker://merkely/change:latest
      env:
        MERKELY_COMMAND: log_approval
        MERKELY_FINGERPRINT: docker://${{ env.IMAGE_TAGGED }}
        MERKELY_OLDEST_SRC_COMMITISH: origin/production
        MERKELY_NEWEST_SRC_COMMITISH: ${{ github.event.inputs.deploy_commit }}
        MERKELY_DESCRIPTION: "Approval created by ${GITHUB_ACTOR} on github"
        MERKELY_SRC_REPO_ROOT: ${{ github.workspace }}
        MERKELY_IS_APPROVED: "TRUE"
        MERKELY_OWNER: ${{ env.MERKELY_OWNER }}
        MERKELY_PIPELINE: ${{ env.MERKELY_PIPELINE }}
        MERKELY_API_TOKEN: ${{ secrets.MERKELY_API_TOKEN }}





