name: Tag with jira ticket

on:
  pull_request:
    types: [closed]

jobs:
  on-merge:
    name: Tag on merge
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Tag with jira ticket from branch name
        run: |
          BRANCH=${{ github.head_ref }}
          # Jira issue keys consist of [project-key]-[sequential-number]
          # project key must be at least 2 characters long and start with an uppercase letter
          # more info: https://support.atlassian.com/jira-software-cloud/docs/what-is-an-issue/#Workingwithissues-Projectandissuekeys
          JIRA_TAG=$(echo "$BRANCH" | grep -oE '[A-Z][A-Z0-9]{1,9}-[0-9]+')
          if [ -n "$JIRA_TAG" ]; then
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            echo "Found jira ticket in branch name '${JIRA_TAG}'"
            git notes add -m "Jira ticket: ${JIRA_TAG}" ${{ github.sha }}
            git push origin ${{ github.sha }}:refs/notes/
          else
            echo "No jira ticket in branch name"
          fi
